[package]
name = "lumin/markdowner"
description = "A library for translation of markdown and Roblox rich text"
version = "0.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
